---
AWSTemplateFormatVersion: '2010-09-09'
Description: This template builds an Amazon Linux EC2 Instance
Metadata:
  Instances:
    Description: 'Building and provisioning Amazon Linux 2 for video demo '
Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
    - t2.micro
    - t2.small
    - t2.medium
    Description: Enter t2.micro, t2.small, or t2.medium. Default is t2.micro.
  ImageID:
    Type: String
    Default: ami-0b69ea66ff7391e80
    AllowedValues:
    - ami-0b69ea66ff7391e80
    Description: 'AMI limited for starter launch to : ami-0b69ea66ff7391e80 '
Resources:
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        Ref: ImageID
      InstanceType:
        Ref: InstanceType
Outputs:
  InstanceId:
    Description: Id of the instance built in demo stack
    Value:
      Ref: myEC2Instance
