---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon Linux EC2 Instance'
Metadata:
  Instances:
    Description: 'EC2 CloudFormation video demo'
Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
    - t2.micro
    - t2.small
    - t2.medium
    Description: 't2.micro, t2.small, or t2.medium'
  ImageID:
    Type: String
    Default: ami-0b69ea66ff7391e80
    AllowedValues:
    - ami-0b69ea66ff7391e80
    Description: 'AMI ami-0b69ea66ff7391e80'
# See the advanced template for an example for Mappings, Condtions, and Transforms
# Mappings - Fn::FindInMap  
# Conditions -  Fn::Equals,Fn::And,Fn::If,Fn::Not,Fn::Or
# Transform - AWS::Serverless,
# See the advanced template for an example
Resources:
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType:
        Ref: InstanceType
      ImageId:
        Ref: ImageID
Outputs:
  InstanceId:
    Description: 'ID of the instance in demo stack'
    Value:
      Ref: myEC2Instance
